# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from app.main.rpc.protos import users_pb2 as app_dot_main_dot_rpc_dot_protos_dot_users__pb2


class UsersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateUser = channel.unary_unary(
        '/users.Users/CreateUser',
        request_serializer=app_dot_main_dot_rpc_dot_protos_dot_users__pb2.CreateUserRequest.SerializeToString,
        response_deserializer=app_dot_main_dot_rpc_dot_protos_dot_users__pb2.CreateUserResult.FromString,
        )
    self.GetUsers = channel.unary_stream(
        '/users.Users/GetUsers',
        request_serializer=app_dot_main_dot_rpc_dot_protos_dot_users__pb2.GetUsersRequest.SerializeToString,
        response_deserializer=app_dot_main_dot_rpc_dot_protos_dot_users__pb2.GetUsersResult.FromString,
        )


class UsersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUsers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UsersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=app_dot_main_dot_rpc_dot_protos_dot_users__pb2.CreateUserRequest.FromString,
          response_serializer=app_dot_main_dot_rpc_dot_protos_dot_users__pb2.CreateUserResult.SerializeToString,
      ),
      'GetUsers': grpc.unary_stream_rpc_method_handler(
          servicer.GetUsers,
          request_deserializer=app_dot_main_dot_rpc_dot_protos_dot_users__pb2.GetUsersRequest.FromString,
          response_serializer=app_dot_main_dot_rpc_dot_protos_dot_users__pb2.GetUsersResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'users.Users', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
